genome_reference:
    "basepath": "../data/reads"
    "provider": "ucsc"
    "release": "hg19"

"genome_fasta": "hg19.fasta"

mirna_ref: "../data/ref/miRNA/miRBase_main_mature.fasta"
mirna_ref_precursors: "../data/ref/miRNA/miRBase_main_precursors.fasta"
mirna_other: "../data/ref/miRNA/miRBase_other_mature.fasta"

samples:
    SRR060981: "../data/reads/smallrna/SRR060981.fastq.gz"
    SRR060982: "../data/reads/smallrna/SRR060982.fastq.gz"
    SRR060983: "../data/reads/smallrna/SRR060983.fastq.gz"
    SRR060984: "../data/reads/smallrna/SRR060984.fastq.gz"
    SRR060985: "../data/reads/smallrna/SRR060985.fastq.gz"
    SRR060986: "../data/reads/smallrna/SRR060986.fastq.gz"

rules:
    trim_galore_se:
        params: "--small_rna --dont_gzip"
    mirdeep2_alignment:
        params: "-e -h -j -l 18 -m -v"
    mirdeep2_identification:
        params: "-t hsa -P -b 0 -v"
