genome_reference:
    "basepath": "path_to_references_data"
    "provider": "ucsc"
    "release": "hg19"

"genome_fasta": "ucsc.hg19.fasta"

mirna_reference:
    "basepath": "path_to_references_data"
    "provider": "mirbase"
    "release": "22"

mirna_ref: "miRBase_GRCh38_mature.fasta"
mirna_ref_precursors: "miRBase_GRCh38_precursors.fasta"
mirna_other: "miRBase_GRCm38_mature.fasta"


samples:
    16_Mock_cell_T0_R1: /u/puva/scratch/incoming/batch17-0046/16_Mock_cell_T0_R1.fastq.gz
    SRR060981: reads/smallrna/SRR060981.fastq.gz
    SRR060982: reads/smallrna/SRR060982.fastq.gz
    SRR060983: reads/smallrna/SRR060983.fastq.gz
    SRR060984: reads/smallrna/SRR060984.fastq.gz
    SRR060985: reads/smallrna/SRR060985.fastq.gz
    SRR060986: reads/smallrna/SRR060986.fastq.gz

rules:
    trim_galore_se:
        params: "--small_rna --dont_gzip"
    mirdeep2_alignment:
        params: "-e -h -j -l 18 -m -v"
    mirdeep2_identification:
        params: "-t hsa -P -b 0 -v"
